<table<%=$vars['attributes']%>>
<colgroup>
    <%_.each($vars['columns'], function($v) {%>
    <col class="col-<%=$v['col']%>">
    <%});%>
</colgroup>
<thead>
<tr>
    <%_.each($vars['columns'], function($v) {%>
    <th class="col-<%=$v['col']%>"><%=$v['name']%></th>
    <%});%>
</tr>
</thead>
<tbody>
<%_.each($vars['data'], function($row) {%>
<tr class="<%=$vars['baseClass']%>-item">
    <%_.each($row, function($v, $k) {%>
    <td class="col-<%=$vars['columns'][$k]['col']%><%=!_.isUn($v['c'])  ?  " $v['c']"  :  ""%>">
    <%=$v['val']%>
    </td>
    <%});%>
</tr>
<%});%>
</tbody>
</table>